Html
Jbar91/Final-Proyect pull request #2
Opened 2021-08-12 08:48 UTC by Jbar91

The HTML front page has been created and styled in this part of the project.

2021-08-13 15:18 UTC, Flordelola commented
Para mejorar temas de Github:
- Nombre de la rama tiene que ser más explicativa
- Título del PR debe de indicar que nos encontraremos en este PR.
- Hacer uso de las herramientas de Reviewers, assignee y labels para tener el PR identificado, y así a la hora de filtrar los involucrados tengamos referencias al PR.

<img width="342" alt="Captura de pantalla 2021-08-13 a las 16 16 18" src="https://user-images.githubusercontent.com/27810497/129381221-f309c31a-5929-4007-8c27-f3a32bf0cdf6.png">
<img width="339" alt="Captura de pantalla 2021-08-13 a las 16 16 11" src="https://user-images.githubusercontent.com/27810497/129381224-735ed170-89ed-4e3d-acb6-d1c130e9c952.png">
<img width="385" alt="Captura de pantalla 2021-08-13 a las 16 16 05" src="https://user-images.githubusercontent.com/27810497/129381228-0d767174-e935-43a2-a623-0540025d79f4.png">

2021-08-13 15:20 UTC, Flordelola commented
Muy buen avance del proyecto, !vas a buen ritmo! Congrats por incluir router desde ya 

![](
https://media.giphy.com/media/w1otEhQ00WdWg/giphy.gif
)

2021-08-13 15:25 UTC, Flordelola requested changes
@Jbar91 Muy buen avance del proyecto, ¡vas a buen ritmo! Congrats por incluir router desde ya 

![](
https://media.giphy.com/media/w1otEhQ00WdWg/giphy.gif
)

2021-08-13 15:25 UTC, Flordelola commented on store/src/views/Experiments.vue
> +import json from "@/assets/articles.json";
La importación de este archivo está dando fallo al levantar vue porque no encuentra el archivo en la ruta 
<img width="807" alt="Captura de pantalla 2021-08-13 a las 15 52 18" src="https://user-images.githubusercontent.com/27810497/129375806-e65f466e-595e-4cc4-9b69-d415ac81461d.png">

2021-08-13 15:25 UTC, Flordelola commented on store/src/views/BuyItemsPage.vue
> +  <v-footer height="90">
Explora una manera de no tener que repetir en todas las views(pages) los componentes footer y header

2021-08-13 15:25 UTC, Flordelola commented on store/src/App.vue
> +    <v-main>
Estás usando la etiqueta <main> para englobar todos los elementos de tu HTML. Recuerda la semántica y el uso de cada tag del html. 

<img width="410" alt="Captura de pantalla 2021-08-13 a las 16 01 36" src="https://user-images.githubusercontent.com/27810497/129377484-272023b3-5b67-4b71-b3fc-138c202d6ebb.png">

También esto podría estar afectando a la altura de tu página dejando espacios en blanco abajo, para que revises algún height, min-height que podría estarte afectando.
<img width="1190" alt="Captura de pantalla 2021-08-13 a las 16 00 18" src="https://user-images.githubusercontent.com/27810497/129377498-0cd93045-867e-4535-9047-aafac4e0bb87.png">

2021-08-13 15:25 UTC, Flordelola commented on store/src/components/BuyItems.vue
> +<template>
No entendemos la finalidad del componente de Buy Items ya que la iterfaz es para empleados. Si no lo vas a necesitar, puedes borrar esta funcionalidad

2021-08-13 15:25 UTC, Flordelola commented on store/src/components/StorageComp.vue
> +    <v-row class="mt-7">
Revisa el responsive para mobile de tus elementos porque quizás tenerlo todo en una única fila no es el mejor recurso
![Screenshot 2021-08-13 at 16-08-26 store](https://user-images.githubusercontent.com/27810497/129379804-24b8b1a7-646b-4230-b3a8-924869de763e.png)

2021-08-13 15:25 UTC, Flordelola commented on store/src/components/Navbar.vue
> +    <v-img
Recuerda de añadir enlace a tu logo de empresa para que siempre tengamos acceso a la Home

2021-08-13 15:25 UTC, Flordelola commented on store/src/components/Footer.vue
> +      <p>Made by: elyonson</p>
Te recomendamos hacer uso de listados para los elementos del footer

2021-08-15 11:20 UTC, Jbar91 commented on store/src/views/Experiments.vue
> +import json from "@/assets/articles.json";
El problema relacionado con este archivo ya lo resolví, era que no estaba incluido en los archivos en el repo.

2021-08-15 11:23 UTC, Jbar91 commented on store/src/components/BuyItems.vue
> +<template>
La finalidad de ese componente es el simular cuando en la tienda tienen que comprar nuevos artículos. Pero ahora que lo mencionas no se si dejarlo y que siga simulando el añadir un nuevo articulo al inventario o eliminarla y solamente dejar el de añadir más artículos ya existentes.

2021-08-16 10:31 UTC, Flordelola commented on store/src/components/BuyItems.vue
> +<template>
No incluyas esa funcionalidad por ahora, y centrate en añadir y eliminar artículos al inventario existente

2021-08-16 17:20 UTC, Jbar91 commented on store/src/components/BuyItems.vue
> +<template>
Vale, me centrare en cambiar a esas funcionalidades entonces.

2021-08-16 17:22 UTC, Jbar91 commented on store/src/components/StorageComp.vue
> +    <v-row class="mt-7">
Que tipo de display seria mejor aquí?  Ponerlos en cuadros uno al lado del otro y que solo salga el nombre del artículo y la cantidad?

2021-08-17 07:04 UTC, TeresaMarbanCastro commented on store/src/components/StorageComp.vue
> +    <v-row class="mt-7">
Que la palabra no se corte

2021-08-17 10:31 UTC, Jbar91 commented on store/src/components/StorageComp.vue
> +    <v-row class="mt-7">
Vale, lo he cambiado a esta manera. Pero hay artículos que tienen un nombre muy largo, como hago en ese caso?
<img width="320" alt="Screenshot 2021-08-17 122834" src="https://user-images.githubusercontent.com/80650048/129710675-5bb01357-859f-4822-a87a-2b46196a3fde.png">

2021-08-18 16:43 UTC, Flordelola commented on store/src/App.vue
> +    <v-main>
Bien, esto ya está corregido

2021-08-18 16:46 UTC, Flordelola commented on store/src/components/StorageComp.vue
> +    <v-row class="mt-7">
Vemos que has cambiado el layout y ahora el responsive está mejor, solo ten en cuenta que la imagen queda muy pegada al margen. Aunque el Vuetify te ponga unos margenes y padding, siempre puedes sobreescribirlos en tu css

![Captura de pantalla 2021-08-18 a las 17 44 39](https://user-images.githubusercontent.com/27810497/129938676-6fc9cbc5-f920-4d9d-8e14-79d9b3e99674.png)

2021-08-18 16:46 UTC, Flordelola commented on store/src/components/Navbar.vue
> +    <v-img
Perfecto, enlace añadido

2021-08-18 16:47 UTC, Flordelola commented on store/src/components/Footer.vue
> +      <p>Made by: elyonson</p>
Bien aplicado el cambio de listados

2021-08-18 16:47 UTC, Flordelola approved these changes
Perfecto los cambios. Para la próxima usa un título del PR más explicativo.. por el resto todo bien

2021-08-18 16:48 UTC, merged