Adding and removing items development, login implementation and specific item view
Jbar91/Final-Proyect pull request #4
Opened 2021-08-25 19:07 UTC by Jbar91

En este PR he creado la funcionalidad de añadir y eliminar cantidad de los artículos simulando su venta o compra, se creó un view de login que tiene unos datos fijos para simular un usuario y contraseña, en el mismo se revisa la igualdad de los 2 datos para permitir o denegar el acceso. Una vez iniciado sesión el usuario tiene la opción de hacer logout. La vista especifica del item seleccionado hace un pequeño display del mismo dando su imagen, precio, cantidad y categoría.

2021-08-27 14:05 UTC, marcosignorello commented on store/src/components/AddItems.vue
>                    :key="item"
En el caso de Key, creo que es mejor usar un valor primitivo aunque te permite de usar un objecto.
![image](https://user-images.githubusercontent.com/4735277/131105206-62974f89-3c47-4dca-9ebc-6a8ed3b91ca4.png)

2021-08-27 14:07 UTC, marcosignorello commented on store/src/components/AddItems.vue
> +              "
Creo que es mejor tener una funcion unica en este trozo de codigo que incluye todas la acciones que se ejecutan una vez que el usuario pincha el boton: 
Ejemplo :  handleOnClick 
function handleOnClick() {
  add();
 // todo el resto del codigo
}

2021-08-27 14:13 UTC, marcosignorello commented on store/src/components/AddItems.vue
>        <v-card width="500">
Esto es comentario sobre el nombre del componente, creo ya se puede cambiar en una manera que reflecta bien lo que va a gestionar. En este caso creo no solo esta gestionando el Add pero también el vender items. Es importante dar un nombre que explica bien el componente y lo que me espero de este componente. Una parte muy importante del desarrollo no es solo crear nuevas funcionalidades, es también mantener lo que esta ya hecho así que dejar un código legible y fácil de mantener es muy importante a largo plazo.

2021-08-27 14:15 UTC, marcosignorello commented on store/src/components/StorageComp.vue
> +                class="example"
class="example" 
esto esta bien?

2021-08-27 14:16 UTC, marcosignorello commented on store/src/views/Items.vue
> +<template>
Esto puede ser Item como que es un template de un item solo.

2021-08-27 14:18 UTC, marcosignorello commented on store/src/views/Items.vue
> +  computed: {
Supongo que esto no tiene que estar aquí, no?
Para que necesitas un scrollTo?

2021-08-27 14:19 UTC, marcosignorello commented on store/src/views/Items.vue
> +}
Creo en este caso es mejor tener una clase y no un estilo genérico para todos los tag P.

2021-08-27 14:21 UTC, marcosignorello commented on store/src/views/Log.vue
> +    <v-container v-if="!status" class="bg-grey-lighten-2 log-inputs">
Mi opinión es en caso de booleanos se entiende mejor si es con el verbo Ejemplo isOnline/isOffline y asi mas.
Un estado puede tener diferentes valores o n valores y un condición basada en un boolean puede ser solo true o false.

2021-08-27 14:34 UTC, marcosignorello commented on store/src/views/Log.vue
> +      }
Creo que esta función se puede simplificar,
```
      if (this.username === this.user && this.password === this.pass) {
        sessionStorage.setItem("Logged", JSON.stringify(true));
        this.cancel();
      } else {
        this.message = "Incorrect username and/or password, please try again";
        this username = "";
        this.password = "";
      }
```

2021-08-27 14:36 UTC, marcosignorello commented on store/src/views/Log.vue
> +    },
que pasa si history -1 es otro sitio?

2021-08-27 14:40 UTC, marcosignorello commented on store/src/views/Storage.vue
> +      this.products[id].quantity = this.products[id].quantity + amountSold;
tiene que ser " this.products[id].quantity = this.products[id].quantity - amountSold;" no?

2021-08-27 14:42 UTC, marcosignorello commented on store/src/views/Storage.vue
> +      this.products[id].quantity = this.products[id].quantity + amountSold;
Otra cosa es amountSold nunca puede ser mas de quantity.

2021-08-27 14:45 UTC, marcosignorello requested changes
Buen trabajo Joseba, he dejado algunos comentario que creo no te va a tomar muchísimo trabajo.
Para cualquier dudas me comentas aquí o por Slack.

2021-08-27 16:43 UTC, Flordelola commented on store/src/components/AddItems.vue
> +              "
Complementando la review de Marco, sugerimos que tengas dos componentes diferentes para addItem or substractItem.. y un click por cada acción

2021-08-27 16:46 UTC, Flordelola commented on store/src/views/Log.vue
> +    <v-container v-if="!status" class="bg-grey-lighten-2 log-inputs">
También sobre este componente. Si hay un login entonces mostrar el nombre del usuario en el header por ejemplo, al lado de una acción de logout. Tener que pinchar en un enlace para luego pinchar en otro para hacer un logout es redundante.

en HEADER:
Login successful: NombreUser - icono de logout 
Login: icono de Login

2021-08-27 17:16 UTC, Flordelola requested changes
De acuerdo con Marco que has hecho un buen trabajo, ambos hemos revisado en detalle tu proyecto y el código. Yo ahora te pongo un resumen de aspectos a mejorar sobre todo a nivel de UX que hemos estado revisando:

1. Mejoras generales con el layout de los cards de los items. No es totalmente responsive y eso se debe a que hay elementos que se salen fuera del card

2. Funcionalidad `manage items` más sencilla, dividir las acciones en 2 componentes. También sería interesante tener la opción de `manage item` dentro del preview del producto 
<img width="1377" alt="Captura de pantalla 2021-08-27 a las 10 21 13" src="https://user-images.githubusercontent.com/27810497/131161942-82dbad84-7aff-4a70-a1c6-63b3918115b3.png">
<img width="1421" alt="Captura de pantalla 2021-08-27 a las 17 56 24" src="https://user-images.githubusercontent.com/27810497/131162500-7525b4c1-ad2b-4b8a-a1b3-0e896c2fbf83.png">


3. Feedback al usuario una vez que la acción de añadir o substraer va bien o va mal. No hay manera fácil de saber la cantidad que había de un producto y en cuanto ha cambiado. Si eliges un producto, estaría bien mostrar su total y cuando se realiza la acción de add or substract que se vea reflejado ese cambio.

4. La funcionalidad `manage items` tiene que ser visible solo para un usuario admin, es decir un usuario que tenga cuenta en la plataforma. De otra manera solo debería de ser un app de consulta sobre el inventario. 

5. Hay un bug en Chrome IOs con el evento del selector y la preview del item. 
- El filtro del producto no se ejecuta cuando elegimos el producto, solo cuando volvemos a pinchar en el selector.
- No se muestra una preview del producto: no hay carga del componente en el html
<img width="1074" alt="Captura de pantalla 2021-08-27 a las 17 59 38" src="https://user-images.githubusercontent.com/27810497/131162924-526998f9-82b3-4f39-8406-d78370c5f7c9.png">

6. Filtro productos: Que siempre esté por defecto `All` en vez de campo vacío 
<img width="1439" alt="Captura de pantalla 2021-08-27 a las 18 01 21" src="https://user-images.githubusercontent.com/27810497/131163075-b878f1ff-2eda-4d8d-b9f0-2daa7f2cecac.png">

7. Falta algún enlace para cerrar la preview del producto, solo podemos acceder al resto de productos si pinchamos en el icono de Home.
<img width="1437" alt="Captura de pantalla 2021-08-27 a las 18 02 19" src="https://user-images.githubusercontent.com/27810497/131163226-653ab0ee-ac61-4191-a242-6fb22493da0c.png">

8. (Esto puede ser para más adelante):  Rutas de los productos: En vez del número de ID, es mejor tener el nombre del producto 
<img width="1137" alt="Captura de pantalla 2021-08-27 a las 18 02 25" src="https://user-images.githubusercontent.com/27810497/131163230-0a36f64e-6997-455f-9d4f-46d72cbfe0ae.png">

9. (Esto puede ser para más adelante): Mostrar el filtro de los productos solo en el componente donde están todos los productos, no tiene ninguna funcionalidad en el componente de la preview del producto, login, manage items o los componentes a los cuales accedemos desde el footer. 

Y un tip que debimos mencionarte antes: Los PR es mejor separarlos por mejoras/features específicas, es decir no combinar un commit que cambia la imagen del logo con un commit que añade una funcionalidad como addItem. O inclusive las funcionalidades: un PR para manage items y otro PR para login/logout. Esto hace más fácil la revisión para tus compañer@s y así también podemos ir dando salida a ramas. Por ahora tienes cambios relacionados a maquetación que todavía no podemos aprobarte porque hay otros cambios de la funcionalidad que necesitas modificar/ mejorar en este PR.

Si quieres practicar sobre la separación de PR en cambios específicos, te proponemos que uses `cherry-pick` para mover commits a otra rama y abrir otro PR con esos cambios. Una vez has hecho el `cherry pick`, puedes borrar los commits de este PR.

Parecen muchos cambios 😄, pero bueno, es normal cuando se está haciendo una aplicación desde 0.

![](https://media.giphy.com/media/dJ0luiI4Hu90BJGNMH/giphy.gif?cid=ecf05e475dy7d79klw4j4q59e3znskt1gtk7t0lhbfucdnk6&rid=giphy.gif&ct=g)

2021-08-28 10:56 UTC, Jbar91 commented on store/src/components/AddItems.vue
>                    :key="item"
He cambiado el valor del key por item.name el cual sería el nombre de cada elemento específico.

2021-08-28 10:58 UTC, Jbar91 commented on store/src/components/AddItems.vue
> +              "
He cambiado por una función que contiene las dos acciones a realizar. Los otros cambios con respecto a que sean 2 componentes diferentes para cada acción los añadiré luego.

2021-08-28 10:59 UTC, Jbar91 commented on store/src/components/AddItems.vue
>        <v-card width="500">
Lo he modificado a ManageItems ya que esas son las acciones que se realizan

2021-08-28 11:00 UTC, Jbar91 commented on store/src/components/StorageComp.vue
> +                class="example"
Esto fue un error, se quedo ese nombre mientras intentaba realizar una prueba (error de mi parte por poner un mal nombre desde un principio), pero ya lo he cambiado

2021-08-28 11:01 UTC, Jbar91 commented on store/src/views/Items.vue
> +<template>
He modificado el nombre del archivo a view ya que ciertamente es solo un item del cual se hace el display

2021-08-28 11:03 UTC, Jbar91 commented on store/src/views/Items.vue
> +  computed: {
Lo he eliminado ya que ciertamente no cumplía ninguna función.

2021-08-28 11:06 UTC, Jbar91 commented on store/src/views/Items.vue
> +}
Lo modifique por un clase que describe su función

2021-08-28 11:08 UTC, Jbar91 commented on store/src/views/Log.vue
> +    <v-container v-if="!status" class="bg-grey-lighten-2 log-inputs">
Cambié el valor de booleano a como tú me indicaste que sea con verbos. La parte del login al lado del icono la implementaré ahora.

2021-08-28 11:11 UTC, Jbar91 commented on store/src/views/Log.vue
> +    },
Lo he cambiado por un router.push() a una ruta especifica dentro de la app. No había tomado en cuenta ese detalle de que history -1 fuera otro sitio.

2021-09-02 16:15 UTC, closed without merging